 name: dbt run
 
 on:
   push:
     branches:
       - main
   pull_request:
     branches:
       - main
 
 jobs:
   dbt_to_snowflake:
      name: push to snowflake
      runs-on: ubuntu-latest
      
      steps:
      - run: pip install  dbt-core dbt-snowflake
      - name: Checkout repository      
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
#       - name: Run Yarn 
#         run: yarn
      - name: Run dbt
#         run: yarn test
        run: dbt run
    
