 name: dbt run
 
 on: push
 
 jobs:
   dbt_to_snowflake:
      name: push to snowflake
      runs-on: ubuntu-latest
      
      steps:
        - run: pip install  dbt-core dbt-snowflake
        - run: cd /home/runner/work/dbt_development
        - run: ls -ld /home/runner/work/dbt_development
        - run: dbt run
    
