 name: dbt run
 
 on:
   push:
     branches:
       - main
   pull_request:
     branches:
       - main
 
 jobs:
   dbt_to_snowflake:
      name: push to snowflake
      runs-on: ubuntu-latest
      
      steps:
      - run: pip install  dbt-core dbt-snowflake
      - name: Checkout repository      
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
#       - name: Run Yarn 
#         run: yarn
      - name: Run dbt
#         run: yarn test
        run: dbt run
    
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status == 'success' }}
          # comma-separated string, send email to
          to: ${{ secrets.GROUP_EMAIL }}
          # from email name
          from: GITHUB
