 name: dbt run
 
 on: push
 
 jobs:
   dbt_to_snowflake:
      name: push to snowflake
      runs-on: ubuntu-latest
      
      steps:
        - run: pip install  dbt-core dbt-snowflake
        - run: cd .dbt/
        - run: dbt run
    
